language: bash
os: linux
service:
  - docker
before_script: docker pull bats/bats:latest
script:
  - ./shellcheck.sh
  - export PATH="$PATH:${PWD}"
  - dotbare finit -u https://github.com/kazhala/dotfiles.git
  - docker run -it -v "${PWD}:/code" bats/bats:latest --tap ./tests
