language: bash
os: linux
service:
  - docker
script:
  - ./shellcheck.sh
  - docker image build -t kazhala/dotbare:test -f tests/Dockerfile .
  - docker container run -it --rm --name dotbare kazhala/dotbare:test
