version: 0.2

phases:
  install:
    commands:
      - echo Installing shellcheck ...
      - yum update -y
      - yum install ShellCheck -y
  build:
    commands:
      - echo Checking script compliance
      - ./shellcheck.sh
