version: 0.2

phases:
  install:
    commands:
      - echo Installing shellcheck ...
      - apt-get update -y
      - apt-get install shellcheck -y
  build:
    commands:
      - echo Checking script compliance
      - ./shellcheck.sh
