version: 0.2

phases:
  install:
    commands:
      - echo Installing shellcheck ...
      - apt-get update -y
      - apt-get install shellcheck -y
  build:
    commands:
      - echo Checking script compliance
      - ./shellcheck.sh
      - echo Building docker url image ...
      - docker image build --build-arg MIGRATE=url -t kazhala/dotbare:testurl -f tests/Dockerfile .
      - echo Running bats unittest ...
      - docker container run -i --rm --name dotbare kazhala/dotbare:testurl
      - echo Building docker bare image ...
      - docker image build --build-arg MIGRATE=bare -t kazhala/dotbare:testbare -f tests/Dockerfile .
      - echo Running bats unittest ...
      - docker container run -i --rm --name dotbare kazhala/dotbare:testbare
