version: 0.2

phases:
  install:
    commands:
      - echo Installing shellcheck ...
      - yum update -y
      - yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - yum-config-manager --enable epel
      - yum install ShellCheck -y
  build:
    commands:
      - echo Checking script compliance
      - ./shellcheck.sh
