name: ci

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        node-version: [10]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g bats
      - run: ./dotbare finit -u https://github.com/kazhala/dotfiles.git
      - run: bats tests
      - run: rm -rf "$HOME"/.cfg
      - run: export confirm='y' && ./dotbare finit
      - run: bats tests
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install bats
      - run: ./dotbare finit -u https://github.com/kazhala/dotfiles.git
      - run: bats tests
      - run: rm -rf "$HOME"/.cfg
      - run: export confirm='y' && ./dotbare finit
      - run: bats tests
