name: Docker Image CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kazhala/dotbare
        tag_with_sha: true

